### ISSUE TITLE
Methods that take a ReadOnlySpan<byte> string assume the string is null-terminated

### ISSUE THREAD

**Issue by PJB3005** [amerkoleci/Alimer.Bindings.SDL#11]
https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/58a789e505934ac64de9d9bff6f48f5b2bb7a235/src/Alimer.Bindings.SDL/SDL.cs#L536-L542

Assuming that the input span is null-terminated is not safe. For example:

```cs
var name = "Drizzle3D"u8;
name = name[..1];

SDL_SetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, name);
```

This will set the title to the full "Drizzle3D" string, even though only the first letter was passed in.

**Comment by amerkoleci** [comment]
Version `3.7.0` handles string marshal in automatic way, fixed now!
