### ISSUE TITLE
LeftShirt & RightShirt

### ISSUE THREAD

**Issue by Zorbn** [amerkoleci/Alimer.Bindings.SDL#13]
Two funny typos :) https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/fe7344dcb65e72e1a1772b1cf1c0594e846ee49e/src/Generator/CsCodeGenerator.Enum.cs#L113

**Comment by amerkoleci** [comment]
Nice catch :)
Will fix it once I'm back from vacation. 

Thanks!

**Comment by amerkoleci** [comment]
Fixed with latest commit and version 3.7.2 comming
