### ISSUE TITLE
Duplicate Structs & Missing methods on autogenerated code

### ISSUE THREAD

**Issue by LetterN** [amerkoleci/Alimer.Bindings.SDL#5]
The auto generated code is making duplicated structs, especially `SDL_Event` related ones

https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/f9d5ae87f795c276761184fee0251a3a250a664f/src/Alimer.Bindings.SDL/Generated/Structs.cs#L505-L509
https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/f9d5ae87f795c276761184fee0251a3a250a664f/src/Alimer.Bindings.SDL/Generated/Structs.cs#L184-L188

[`SDL_CreateSurfaceFrom`](https://wiki.libsdl.org/SDL3/SDL_CreateSurfaceFrom) also seems to be missing

**Comment by amerkoleci** [comment]
Version [3.4.5](https://www.nuget.org/packages/Alimer.Bindings.SDL/3.4.5) adds support for SDL_surface.h and SDL_pixels.h as well.

Cheers!
