### ISSUE TITLE
SDL not linked properly on linux

### ISSUE THREAD

**Issue by LetterN** [amerkoleci/Alimer.Bindings.SDL#7]
https://github.com/space-wizards/RobustToolbox/pull/4858#issuecomment-1913237594

**Comment by amerkoleci** [comment]
> [space-wizards/RobustToolbox#4858 (comment)](https://github.com/space-wizards/RobustToolbox/pull/4858#issuecomment-1913237594)

Not sure what you mean? I'm building exactly with SDL CMake script from here: https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt

What is the issues?
Feel free to submit PR in case.

Thanks!

**Comment by LetterN** [comment]
Done some testing, is the built (linux) libraries being renamed? built SDL localy and it outputs the same libs only different is the name (for the "main" one, not the symlinked ones)
`libSDL3-0.0.so.0` copied to the release vs `libSDL3.so.0.0.0` from building localy

**Comment by amerkoleci** [comment]
Can you try with recent `3.4.7` and tell me if it works?

**Comment by LetterN** [comment]
doesn't work however i think renamining the `libSDL3.so.0.0.0` to just `libSDL3.so` should be fine, as we dont use the version provided from it  `libSDL3.so.0.[major].[minor]`

**Comment by amerkoleci** [comment]
Version `3.4.8` has been released, can you try?

**Comment by LetterN** [comment]
works properly now, hello word also works without adding/renaming the libSDL3.so
