### ISSUE TITLE
Some friendly overloads of string-returning SDL functions leak memory

### ISSUE THREAD

**Issue by Susko3** [amerkoleci/Alimer.Bindings.SDL#8]
For example, take [`SDL_GetClipboardText()`](https://github.com/libsdl-org/SDL/blob/5b3ee51c6ca94f803a4ca77ce0dce08ee0426f80/include/SDL3/SDL_clipboard.h#L55-L71) which requires the returned pointer to be freed with `SDL_free()`. The friendly overload [`SDL_GetClipboardTextString()`](https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/c1d19a2b8419896f6b573bedac44c85c270425ee/src/Alimer.Bindings.SDL/SDL.Clipboard.cs#L26-L29) never explicitly calls `SDL_free()`, so it must be leaking SDL-allocated memory.

As a general rule of thumb, in C functions that return `char *`, the pointer/string is owned (and should be freed) by the caller; while `const char *` pointers are owned by the callee. The SDL docs and doc comments also mention whether the returned string should be freed or not.

**Comment by amerkoleci** [comment]
Latest version `3.5.0` fixes this, tell me if there is something I've missed out.
