### ISSUE TITLE
Possible out-of-bounds string/array access in `GetUtf8Span()`

### ISSUE THREAD

**Issue by Susko3** [amerkoleci/Alimer.Bindings.SDL#9]
`ReadOnlySpan.IndexOf` is vectorized, meaning that, instead of going byte-by-byte to find the value, it uses SIMD instructions to search multiple bytes (eg. 32) at a time.

Since the code below lies to the runtime about the length of the C string, a vectorized algorithm might access memory past the "end of string" (`\0`) byte (eg. up to 31 bytes with 32-byte vectorization).

https://github.com/amerkoleci/Alimer.Bindings.SDL/blob/7cc86873ce125abf4b8362b9ecd6ce016fcf712b/src/Alimer.Bindings.SDL/SDL.cs#L1060-L1066

**Comment by amerkoleci** [comment]
What fix do you propose?
Feel free to submit PR in case.

Thanks!

**Comment by Susko3** [comment]
I would suggest using https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostringutf8?view=net-8.0, or manually going byte-by-byte if the max length is not known.

**Comment by amerkoleci** [comment]
The code was adopted from tanners repo https://github.com/terrafx/terrafx/blob/main/sources/Core/Utilities/MarshalUtilities.cs#L109o

**Comment by PJB3005** [comment]
I am going to guess the reason the code from TerraFX is safe is that the vectorized `IndexOf` operation runs in *aligned* blocks, meaning it is never possible for a block to cross a page boundary (and therefore AV). This is probably an implementation detail that Tanner is aware of being a .NET runtime dev themselves.

If you want the proper API for this exact purpose, it's `MemoryMarshal.CreateReadOnlySpanFromNullTerminated()`.

**Comment by amerkoleci** [comment]
Version `3.7.0` handles string marshal in automatic way, fixed now!
